Aremote: Enumerating objects: 11, done. remote: Counting objects: 100% (11/11), done. remote: Compressing objects: 100% (9/9), done. remote: Total 9 (delta 6), reused 0 (delta 0), pack-reused 0 (from 0) Unpacking objects: 100% (9/9), 2.74 KiB | 65.00 KiB/s, done. From https://github.com/Ganga2005-prog/myportfolio  * branch            main       -> FETCH_HEAD     d4f1a85..b281966  main       -> origin/main     Auto-merging README.md     CONFLICT (content): Merge conflict in README.md     error: could not apply 4104db7... push code     hint: Resolve all conflicts manually, mark them as resolved with     hint: "git add/rm <conflicted_files>", then run "git rebase     --continue".     hint: You can instead skip this commit: run "git rebase --skip".     hint: To abort and get back to the state before "git rebase", run     "git rebase --abort".     hint: Disable this message with "git config set advice.mergeConflict     false"     Could not apply 4104db7... # push code     PS C:\Users\keshavamurthy\Desktop\myprofile> ^C     PS C:\Users\keshavamurthy\Desktop\myprofile> push code
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 6), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (9/9), 2.74 KiB | 65.00 KiB/s, done.
From https://github.com/Ganga2005-prog/myportfolio
 * branch            main       -> FETCH_HEAD
   d4f1a85..b281966  main       -> origin/main
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
error: could not apply 4104db7... push code
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
hint: Disable this message with "git config set advice.mergeConflict false"
Could not apply 4104db7... # push code
PS C:\Users\keshavamurthy\Desktop\myprofile> ^C
PS C:\Users\keshavamurthy\Desktop\myprofile>git rebase --continue